IF NOT EXISTS (SELECT 1 FROM CUSTOM_INSTRUCTIONS WHERE CUSTOM_INSTRUCTION_ID = 51)
	BEGIN
		SET IDENTITY_INSERT CUSTOM_INSTRUCTIONS ON
		
		INSERT INTO CUSTOM_INSTRUCTIONS
		(
			CUSTOM_INSTRUCTION_ID,
			DEFAULT_INSTRUCTIONS,
			CUSTOM_INSTRUCTIONS,
			INSTRUCTION_LABEL_1,
			[RANK],
			CUSTOM_INSTRUCTION_TYPE_ID,
			HAS_DEFAULT_INSTRUCTIONS,
			HAS_EXPLANATORY_TEXT,
			SUPPRESS_DISPLAY,
			LAST_UPDATE
		)
		VALUES
		(
			51,
			'',
			NULL,
			'',
			1,
			22,
			1,
			0,
			0,
			GETDATE()
		)
		
		SET IDENTITY_INSERT CUSTOM_INSTRUCTIONS OFF
	END