IF NOT EXISTS (
	SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'AUTHORROLE' AND COLUMN_NAME = 'VIEWCIFCHECKRESULT'
	)
	BEGIN
		ALTER TABLE AUTHORROLE 
		ADD VIEWCIFCHECKRESULT bit NOT NULL DEFAULT 0
	END

IF NOT EXISTS (
	SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'REVIEWERROLE' AND COLUMN_NAME = 'VIEWCIFCHECKRESULT'
	)
	BEGIN
		ALTER TABLE REVIEWERROLE 
		ADD VIEWCIFCHECKRESULT bit NOT NULL DEFAULT 0
	END	
	
IF NOT EXISTS (
	SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'EDITORROLE' AND COLUMN_NAME = 'VIEWCIFCHECKRESULT'
	)
	BEGIN
		ALTER TABLE EDITORROLE 
		ADD VIEWCIFCHECKRESULT bit NOT NULL DEFAULT 0
	END
	
IF NOT EXISTS (
	SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'EDITORROLE' AND COLUMN_NAME = 'INITIATECIFCHECK'
	)
	BEGIN
		ALTER TABLE EDITORROLE 
		ADD INITIATECIFCHECK bit NOT NULL DEFAULT 0
	END
	
	
IF NOT EXISTS (
	SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'PUBLISHERROLE' AND COLUMN_NAME = 'VIEWCIFCHECKRESULT'
	)
	BEGIN
		ALTER TABLE PUBLISHERROLE 
		ADD VIEWCIFCHECKRESULT bit NOT NULL DEFAULT 0
	END
	
IF NOT EXISTS (
	SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'PUBLISHERROLE' AND COLUMN_NAME = 'INITIATECIFCHECK'
	)
	BEGIN
		ALTER TABLE PUBLISHERROLE 
		ADD INITIATECIFCHECK bit NOT NULL DEFAULT 0
	END
	
